<center>
    <img src ='./Images/Swiggy_logo.png'width = "250"/>
</center>
<p style="font-size:50px; font-style:bold;text-decoration: underline;color:#fc8019;text-align: center ">
 Swiggy Metro Cities Data Analysis
</p>


## <span style="color:#FC8019;font-size:25px; font-style:bold;"><u><b>About Dataset</b></u></span>

Context:

This dataset contains swiggy registered restaurants details of major metropoliton cities of India. It considered only metropoliton cities with population 4.5 million. As per the Census of India 2011 definition of more than 4 million population, some of the major Metropolitan Cities in India are:


Content:

This Dataset Contains 18 Different Columns which are :

 1.  type --> Contain (F,D,C,P) Means 
         > Fine Restaurants
         > Dessert Restaurants
         > Continental Restaurants
         > Premium Restaurants
 
 2.   id --> Restaurants id                  
 3.   name  --> Restaurants name           
 4.   uuid --> Universally Unique Identifiers
 5.   city -->  Restaurants Belong from City  
 
            * Mumbai (more than 18 Million)
            * Delhi (more than 16 Million)
            * Kolkata (more than 14 Million)
            * Chennai (more than 8.6 million)
            * Bangalore (around 8.5 million)
            * Hyderabad (around 7.6 million)
            * Ahmedabad (around 6.3 million)
            * Pune (around 5.05 million)
            * Surat (around 4.5 million)
            
 6.   area  -->  Restaurants belong from Area              
 7.   avgRating --> Restaurants   Average Rating         
 8.   totalRatingsString --> Restaurants   Total  Rating  string
 9.   cuisines  --> Restaurants   Serving Cuisines (Menu)
 10.  costForTwoStrings  --> Restaurants   Cost for Two 
 11.  deliveryTime    --> Restaurants   Delivery Time
 12.  minDeliveryTime  --> Restaurants  Minimum Delivery Time
 14.  maxDeliveryTime  --> Restaurants  Maximum Delivery Time  
 14.  address  --> Restaurants  address 
 15.  locality  --> Restaurants  locality
 16.  unserviceable --> Restaurants  provide service or not
 17.  veg    --> Restaurants   Serving food veg. or non-veg
 18.  City 


    


<u>Acknowledgements:<u>
Thank you swiggy for the dataset.

In [1]:
# Import Library
import opendatasets as od
import os
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib

import matplotlib.pyplot as plt
%matplotlib inline
import warnings
print("Import Successfully...")

# Setting
warnings.filterwarnings('ignore')
pd.pandas.set_option("display.max_columns",None)
sns.set_style("darkgrid")
matplotlib.rcParams['font.size']=14
matplotlib.rcParams['figure.figsize']=(15,7)
matplotlib.rcParams['figure.facecolor']='#FFFFFF'

print("Setting Successully..")

Import Successfully...
Setting Successully..

In [2]:
# Downloading Dataset from Kaggle for that I am using Opendatasets library

# dataset_url is our  Dataset URL link
dataset_url = 'https://www.kaggle.com/datasets/aniruddhapa/swiggy-restaurants-dataset-of-metro-cities' 

# Download dataset_url with the help of  Opendatasets's download() function
od.download(dataset_url)

print("Dataset has been downloaded......")

Skipping, found downloaded files in ".\swiggy-restaurants-dataset-of-metro-cities" (use force=True to force download)
Dataset has been downloaded......

In [3]:
# The dataset has been downloaded and extracted.
#Extracted File inn data_dir
data_dir = './swiggy-restaurants-dataset-of-metro-cities'

print("Dataset has been Extracted sucessfully......")

Dataset has been Extracted sucessfully......

## <span style="color:#FC8019;font-size:25px; font-style:bold;"><u><b>Data Preparation and Cleaning</b></u></span> 

**The raw data is now obtained. First we need to clean and simplify the data in order to prepare it for Analysis.** 

1. Load the file using Pandas
2. Look at some information about the data & the columns
3. Fix any missing or incorrect values

In [4]:
os.listdir(data_dir)

['.ipynb_checkpoints', 'Swiggy_dataset.csv']

In [5]:
dataset = pd.read_csv('./swiggy-restaurants-dataset-of-metro-cities/Swiggy_dataset.csv')

In [6]:
dataset.head()

,type,id,name,uuid,city,area,avgRating,totalRatingsString,cuisines,costForTwoStrings,deliveryTime,minDeliveryTime,maxDeliveryTime,address,locality,unserviceable,veg,City
0,F,37933,Faasos - Wraps & Rolls,6fe9caf1-02a7-4e66-83bb-1b4ff296b683,Ahmedabad,Vastrapur,4.2,500+ ratings,['Combo' 'Snacks' 'Beverages' 'Desserts' 'Indi...,₹200 FOR TWO,44,44,44,SHOP NO 2 HOTEL SHAHI PALACE VASTRAPUR LAKE AH...,HOTEL SHAHI PALACE,False,False,NaN
1,F,81814,Burger King,10083576-d32d-4a0e-8a82-3236ef342a19,Ahmedabad,Ellisbridge,4.2,1000+ ratings,['American' 'Fast Food'],₹350 FOR TWO,33,33,33,SHOP # 5 GR FLR THIRD EYE 2PANCHAVATI CIRCLE O...,3rd Eye II Ellis Bridge CG Road,False,False,NaN
2,F,107046,Mahalaxmi Pav Bhaji,fbfe3bfa-03fd-4708-b913-06e2c9ee9639,Ahmedabad,Ellisbridge,4.3,500+ ratings,['North Indian'],₹200 FOR TWO,28,28,28,GF 9/10 Dev complexnear parimal charasta opp. ...,C G Road,False,True,NaN
3,F,328315,HIIT Meals,81ab4019-2445-4aef-aff2-04beccd641d9,Ahmedabad,Vishala,--,Too Few Ratings,['Fast Food' 'Combo' 'Snacks' 'North Indian' '...,₹150 FOR TWO,51,51,51,C11 Rajyash Rise Near Vishala Restaurant Vasna...,Vasna,False,False,NaN
4,F,108879,Jay Jalaram Parotha House,994e73e1-7c7c-4ad9-87e7-ecfecd4e36fa,Ahmedabad,Ellisbridge,3.9,100+ ratings,['North Indian'],₹250 FOR TWO,29,29,29,Capital Commercial Centre Near UCO Bank Ashram...,Ashram Road,False,True,NaN

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8691 entries, 0 to 8690
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   type                8691 non-null   object
 1   id                  8691 non-null   int64
 2   name                8691 non-null   object
 3   uuid                8688 non-null   object
 4   city                8691 non-null   object
 5   area                8691 non-null   object
 6   avgRating           8691 non-null   object
 7   totalRatingsString  8691 non-null   object
 8   cuisines            8691 non-null   object
 9   costForTwoStrings   8691 non-null   object
 10  deliveryTime        8691 non-null   int64
 11  minDeliveryTime     8691 non-null   int64
 12  maxDeliveryTime     8691 non-null   int64
 13  address             8682 non-null   object
 14  locality            8681 non-null   object
 15  unserviceable       8685 non-null   object
 16  veg                 8685 non-null   object
 17  City                0 non-null      float64
dtypes: float64(1), int64(4), object(13)
memory usage: 1.2+ MB

In [8]:
dataset.describe()

                  id  deliveryTime  minDeliveryTime  maxDeliveryTime  City
count    8691.000000   8691.000000      8691.000000      8691.000000   0.0
mean   244855.957887     53.959268        53.130480        53.130480   NaN
std    158650.520513     14.290555        13.701142        13.701142   NaN
min       211.000000     20.000000        20.000000        20.000000   NaN
25%     72885.500000     44.000000        44.000000        44.000000   NaN
50%    283560.000000     52.000000        52.000000        52.000000   NaN
75%    393448.500000     64.000000        63.000000        63.000000   NaN
max    466928.000000    109.000000       109.000000       109.000000   NaN

In [9]:
Name_of_Columns = [Column_name for Column_name in dataset.columns]
print("Column Name :\n",Name_of_Columns)

Column Name :
 ['type', 'id', 'name', 'uuid', 'city', 'area', 'avgRating', 'totalRatingsString', 'cuisines', 'costForTwoStrings', 'deliveryTime', 'minDeliveryTime', 'maxDeliveryTime', 'address', 'locality', 'unserviceable', 'veg', 'City']

In [10]:
print(f"Now of Row : {dataset.shape[0]}\n")
print(f"Now of Column : {dataset.shape[1]}\n")

print("Total no. Null value in Column :\n")

for col in dataset.columns:
    if dataset[col].isna().sum()>1:
        print(f"{col} - {dataset[col].isna().sum()}")

Now of Row : 8691

Now of Column : 18

Total no. Null value in Column :

uuid - 3
address - 9
locality - 10
unserviceable - 6
veg - 6
City - 8691

In [11]:
for col in dataset.columns:
    if dataset[col].isna().sum()>1:
        print(f"{col} - ({np.round((dataset[col].isna().mean())*100,4)})% missing Values")

uuid - (0.0345)% missing Values
address - (0.1036)% missing Values
locality - (0.1151)% missing Values
unserviceable - (0.069)% missing Values
veg - (0.069)% missing Values
City - (100.0)% missing Values

In [85]:
dataset_copy=dataset.copy(deep=True)

In [86]:
dataset_copy.head()

,type,id,name,uuid,city,area,avgRating,totalRatingsString,cuisines,costForTwoStrings,deliveryTime,minDeliveryTime,maxDeliveryTime,address,locality,unserviceable,veg,City
0,F,37933,Faasos - Wraps & Rolls,6fe9caf1-02a7-4e66-83bb-1b4ff296b683,Ahmedabad,Vastrapur,4.2,500+ ratings,['Combo' 'Snacks' 'Beverages' 'Desserts' 'Indi...,₹200 FOR TWO,44,44,44,SHOP NO 2 HOTEL SHAHI PALACE VASTRAPUR LAKE AH...,HOTEL SHAHI PALACE,False,False,NaN
1,F,81814,Burger King,10083576-d32d-4a0e-8a82-3236ef342a19,Ahmedabad,Ellisbridge,4.2,1000+ ratings,['American' 'Fast Food'],₹350 FOR TWO,33,33,33,SHOP # 5 GR FLR THIRD EYE 2PANCHAVATI CIRCLE O...,3rd Eye II Ellis Bridge CG Road,False,False,NaN
2,F,107046,Mahalaxmi Pav Bhaji,fbfe3bfa-03fd-4708-b913-06e2c9ee9639,Ahmedabad,Ellisbridge,4.3,500+ ratings,['North Indian'],₹200 FOR TWO,28,28,28,GF 9/10 Dev complexnear parimal charasta opp. ...,C G Road,False,True,NaN
3,F,328315,HIIT Meals,81ab4019-2445-4aef-aff2-04beccd641d9,Ahmedabad,Vishala,--,Too Few Ratings,['Fast Food' 'Combo' 'Snacks' 'North Indian' '...,₹150 FOR TWO,51,51,51,C11 Rajyash Rise Near Vishala Restaurant Vasna...,Vasna,False,False,NaN
4,F,108879,Jay Jalaram Parotha House,994e73e1-7c7c-4ad9-87e7-ecfecd4e36fa,Ahmedabad,Ellisbridge,3.9,100+ ratings,['North Indian'],₹250 FOR TWO,29,29,29,Capital Commercial Centre Near UCO Bank Ashram...,Ashram Road,False,True,NaN

In [87]:
s="F"
if s == "F":
    s=s.replace("F","Fine Dinner")
print(s)

Fine Dinner

In [88]:
dataset_copy['type']

0       F
1       F
2       F
3       F
4       F
       ..
8686    F
8687    F
8688    F
8689    F
8690    F
Name: type, Length: 8691, dtype: object

In [89]:
def replace(data):
    if data =='F':
        return data.replace("F","Fine Restaurants")
    elif data =='D':
        return data.replace("D","Dining Restaurants")
    elif data =='C':
        return data.replace("C","Continental Restaurants")
    else:
        return data.replace("P","Permium Restaurants")

In [90]:
Type = dataset_copy['type'].apply(lambda x: replace(x))

In [91]:
dataset_copy['type'] = Type
dataset_copy.head(5)

,type,id,name,uuid,city,area,avgRating,totalRatingsString,cuisines,costForTwoStrings,deliveryTime,minDeliveryTime,maxDeliveryTime,address,locality,unserviceable,veg,City
0,Fine Restaurants,37933,Faasos - Wraps & Rolls,6fe9caf1-02a7-4e66-83bb-1b4ff296b683,Ahmedabad,Vastrapur,4.2,500+ ratings,['Combo' 'Snacks' 'Beverages' 'Desserts' 'Indi...,₹200 FOR TWO,44,44,44,SHOP NO 2 HOTEL SHAHI PALACE VASTRAPUR LAKE AH...,HOTEL SHAHI PALACE,False,False,NaN
1,Fine Restaurants,81814,Burger King,10083576-d32d-4a0e-8a82-3236ef342a19,Ahmedabad,Ellisbridge,4.2,1000+ ratings,['American' 'Fast Food'],₹350 FOR TWO,33,33,33,SHOP # 5 GR FLR THIRD EYE 2PANCHAVATI CIRCLE O...,3rd Eye II Ellis Bridge CG Road,False,False,NaN
2,Fine Restaurants,107046,Mahalaxmi Pav Bhaji,fbfe3bfa-03fd-4708-b913-06e2c9ee9639,Ahmedabad,Ellisbridge,4.3,500+ ratings,['North Indian'],₹200 FOR TWO,28,28,28,GF 9/10 Dev complexnear parimal charasta opp. ...,C G Road,False,True,NaN
3,Fine Restaurants,328315,HIIT Meals,81ab4019-2445-4aef-aff2-04beccd641d9,Ahmedabad,Vishala,--,Too Few Ratings,['Fast Food' 'Combo' 'Snacks' 'North Indian' '...,₹150 FOR TWO,51,51,51,C11 Rajyash Rise Near Vishala Restaurant Vasna...,Vasna,False,False,NaN
4,Fine Restaurants,108879,Jay Jalaram Parotha House,994e73e1-7c7c-4ad9-87e7-ecfecd4e36fa,Ahmedabad,Ellisbridge,3.9,100+ ratings,['North Indian'],₹250 FOR TWO,29,29,29,Capital Commercial Centre Near UCO Bank Ashram...,Ashram Road,False,True,NaN

In [92]:
cuisines = dataset_copy['cuisines'].apply(lambda x: x.replace(" ",","))
dataset_copy['cuisines'] = cuisines
dataset_copy.head(5)

,type,id,name,uuid,city,area,avgRating,totalRatingsString,cuisines,costForTwoStrings,deliveryTime,minDeliveryTime,maxDeliveryTime,address,locality,unserviceable,veg,City
0,Fine Restaurants,37933,Faasos - Wraps & Rolls,6fe9caf1-02a7-4e66-83bb-1b4ff296b683,Ahmedabad,Vastrapur,4.2,500+ ratings,"['Combo','Snacks','Beverages','Desserts','Indi...",₹200 FOR TWO,44,44,44,SHOP NO 2 HOTEL SHAHI PALACE VASTRAPUR LAKE AH...,HOTEL SHAHI PALACE,False,False,NaN
1,Fine Restaurants,81814,Burger King,10083576-d32d-4a0e-8a82-3236ef342a19,Ahmedabad,Ellisbridge,4.2,1000+ ratings,"['American','Fast,Food']",₹350 FOR TWO,33,33,33,SHOP # 5 GR FLR THIRD EYE 2PANCHAVATI CIRCLE O...,3rd Eye II Ellis Bridge CG Road,False,False,NaN
2,Fine Restaurants,107046,Mahalaxmi Pav Bhaji,fbfe3bfa-03fd-4708-b913-06e2c9ee9639,Ahmedabad,Ellisbridge,4.3,500+ ratings,"['North,Indian']",₹200 FOR TWO,28,28,28,GF 9/10 Dev complexnear parimal charasta opp. ...,C G Road,False,True,NaN
3,Fine Restaurants,328315,HIIT Meals,81ab4019-2445-4aef-aff2-04beccd641d9,Ahmedabad,Vishala,--,Too Few Ratings,"['Fast,Food','Combo','Snacks','North,Indian','...",₹150 FOR TWO,51,51,51,C11 Rajyash Rise Near Vishala Restaurant Vasna...,Vasna,False,False,NaN
4,Fine Restaurants,108879,Jay Jalaram Parotha House,994e73e1-7c7c-4ad9-87e7-ecfecd4e36fa,Ahmedabad,Ellisbridge,3.9,100+ ratings,"['North,Indian']",₹250 FOR TWO,29,29,29,Capital Commercial Centre Near UCO Bank Ashram...,Ashram Road,False,True,NaN

In [93]:
dataset_copy.rename(columns = {'veg':'Vegetarian'}, inplace = True)

In [94]:
dataset_copy.head(5)

,type,id,name,uuid,city,area,avgRating,totalRatingsString,cuisines,costForTwoStrings,deliveryTime,minDeliveryTime,maxDeliveryTime,address,locality,unserviceable,Vegetarian,City
0,Fine Restaurants,37933,Faasos - Wraps & Rolls,6fe9caf1-02a7-4e66-83bb-1b4ff296b683,Ahmedabad,Vastrapur,4.2,500+ ratings,"['Combo','Snacks','Beverages','Desserts','Indi...",₹200 FOR TWO,44,44,44,SHOP NO 2 HOTEL SHAHI PALACE VASTRAPUR LAKE AH...,HOTEL SHAHI PALACE,False,False,NaN
1,Fine Restaurants,81814,Burger King,10083576-d32d-4a0e-8a82-3236ef342a19,Ahmedabad,Ellisbridge,4.2,1000+ ratings,"['American','Fast,Food']",₹350 FOR TWO,33,33,33,SHOP # 5 GR FLR THIRD EYE 2PANCHAVATI CIRCLE O...,3rd Eye II Ellis Bridge CG Road,False,False,NaN
2,Fine Restaurants,107046,Mahalaxmi Pav Bhaji,fbfe3bfa-03fd-4708-b913-06e2c9ee9639,Ahmedabad,Ellisbridge,4.3,500+ ratings,"['North,Indian']",₹200 FOR TWO,28,28,28,GF 9/10 Dev complexnear parimal charasta opp. ...,C G Road,False,True,NaN
3,Fine Restaurants,328315,HIIT Meals,81ab4019-2445-4aef-aff2-04beccd641d9,Ahmedabad,Vishala,--,Too Few Ratings,"['Fast,Food','Combo','Snacks','North,Indian','...",₹150 FOR TWO,51,51,51,C11 Rajyash Rise Near Vishala Restaurant Vasna...,Vasna,False,False,NaN
4,Fine Restaurants,108879,Jay Jalaram Parotha House,994e73e1-7c7c-4ad9-87e7-ecfecd4e36fa,Ahmedabad,Ellisbridge,3.9,100+ ratings,"['North,Indian']",₹250 FOR TWO,29,29,29,Capital Commercial Centre Near UCO Bank Ashram...,Ashram Road,False,True,NaN

In [95]:
dataset_copy.drop(columns=['uuid','city'], inplace=True)

In [96]:
dataset_copy

,type,id,name,area,avgRating,totalRatingsString,cuisines,costForTwoStrings,deliveryTime,minDeliveryTime,maxDeliveryTime,address,locality,unserviceable,Vegetarian,City
0,Fine Restaurants,37933,Faasos - Wraps & Rolls,Vastrapur,4.2,500+ ratings,"['Combo','Snacks','Beverages','Desserts','Indi...",₹200 FOR TWO,44,44,44,SHOP NO 2 HOTEL SHAHI PALACE VASTRAPUR LAKE AH...,HOTEL SHAHI PALACE,False,False,NaN
1,Fine Restaurants,81814,Burger King,Ellisbridge,4.2,1000+ ratings,"['American','Fast,Food']",₹350 FOR TWO,33,33,33,SHOP # 5 GR FLR THIRD EYE 2PANCHAVATI CIRCLE O...,3rd Eye II Ellis Bridge CG Road,False,False,NaN
2,Fine Restaurants,107046,Mahalaxmi Pav Bhaji,Ellisbridge,4.3,500+ ratings,"['North,Indian']",₹200 FOR TWO,28,28,28,GF 9/10 Dev complexnear parimal charasta opp. ...,C G Road,False,True,NaN
3,Fine Restaurants,328315,HIIT Meals,Vishala,--,Too Few Ratings,"['Fast,Food','Combo','Snacks','North,Indian','...",₹150 FOR TWO,51,51,51,C11 Rajyash Rise Near Vishala Restaurant Vasna...,Vasna,False,False,NaN
4,Fine Restaurants,108879,Jay Jalaram Parotha House,Ellisbridge,3.9,100+ ratings,"['North,Indian']",₹250 FOR TWO,29,29,29,Capital Commercial Centre Near UCO Bank Ashram...,Ashram Road,False,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8686,Fine Restaurants,452149,RAJWADU KATHIYAWADI RESTAURANT,Adajan,--,Too Few Ratings,"['Gujarati','Indian','Fast,Food','Pizzas','Bev...",₹300 FOR TWO,77,77,77,R.S.NO.17 PAIKI G.F. OLPAD ROAD NR. RAJ MARBLE...,Adajan,False,True,NaN
8687,Fine Restaurants,411690,Concord Restaurant,Adajan,4,100+ ratings,"['North,Indian']",₹300 FOR TWO,72,72,72,160 TO 1802ND FLOORRAJ HARMONYUGAT-BHESAN RO...,Adajan,False,False,NaN
8688,Fine Restaurants,409122,5 Hot Chillis Pizza & Mocktail bar,Sarthana,--,Too Few Ratings,"['Italian','Fast,Food']",₹200 FOR TWO,70,70,70,SHOP NO 234 ATLANTA MALL SUDAMA CHOWKOPP TULSI...,Sarthana,False,True,NaN
8689,Fine Restaurants,438809,SHIVA GARDEN RESTAURANT,Sarthana,--,Too Few Ratings,['Indian'],₹200 FOR TWO,66,66,66,Shiva Garden Restaurant Lajamni Chowk Shanti N...,Sarthana,False,True,NaN
8690,Fine Restaurants,425118,Waterbomb pani-puri shop,Sarthana,--,Too Few Ratings,['Snacks'],₹155 FOR TWO,67,67,67,12 Ambika pinnacle Lajamni Chowk near savji ko...,Sarthana,False,True,NaN

In [98]:
costForTwoStrings = dataset_copy['costForTwoStrings'].apply(lambda x: x[1:4])
dataset_copy['costForTwoStrings'] = costForTwoStrings
dataset_copy.head(5)

,type,id,name,area,avgRating,totalRatingsString,cuisines,costForTwoStrings,deliveryTime,minDeliveryTime,maxDeliveryTime,address,locality,unserviceable,Vegetarian,City
0,Fine Restaurants,37933,Faasos - Wraps & Rolls,Vastrapur,4.2,500+ ratings,"['Combo','Snacks','Beverages','Desserts','Indi...",200,44,44,44,SHOP NO 2 HOTEL SHAHI PALACE VASTRAPUR LAKE AH...,HOTEL SHAHI PALACE,False,False,NaN
1,Fine Restaurants,81814,Burger King,Ellisbridge,4.2,1000+ ratings,"['American','Fast,Food']",350,33,33,33,SHOP # 5 GR FLR THIRD EYE 2PANCHAVATI CIRCLE O...,3rd Eye II Ellis Bridge CG Road,False,False,NaN
2,Fine Restaurants,107046,Mahalaxmi Pav Bhaji,Ellisbridge,4.3,500+ ratings,"['North,Indian']",200,28,28,28,GF 9/10 Dev complexnear parimal charasta opp. ...,C G Road,False,True,NaN
3,Fine Restaurants,328315,HIIT Meals,Vishala,--,Too Few Ratings,"['Fast,Food','Combo','Snacks','North,Indian','...",150,51,51,51,C11 Rajyash Rise Near Vishala Restaurant Vasna...,Vasna,False,False,NaN
4,Fine Restaurants,108879,Jay Jalaram Parotha House,Ellisbridge,3.9,100+ ratings,"['North,Indian']",250,29,29,29,Capital Commercial Centre Near UCO Bank Ashram...,Ashram Road,False,True,NaN

In [112]:
totalRatingsString = dataset_copy['totalRatingsString'].apply(lambda s : s.replace(s[-8:],''))
dataset_copy['totalRatingsString'] = totalRatingsString
dataset_copy.head(5)

,type,id,name,area,avgRating,totalRatingsString,cuisines,costForTwoStrings,deliveryTime,minDeliveryTime,maxDeliveryTime,address,locality,unserviceable,Vegetarian,City
0,Fine Restaurants,37933,Faasos - Wraps & Rolls,Vastrapur,4.2,500+,"['Combo','Snacks','Beverages','Desserts','Indi...",200,44,44,44,SHOP NO 2 HOTEL SHAHI PALACE VASTRAPUR LAKE AH...,HOTEL SHAHI PALACE,False,False,NaN
1,Fine Restaurants,81814,Burger King,Ellisbridge,4.2,1000+,"['American','Fast,Food']",350,33,33,33,SHOP # 5 GR FLR THIRD EYE 2PANCHAVATI CIRCLE O...,3rd Eye II Ellis Bridge CG Road,False,False,NaN
2,Fine Restaurants,107046,Mahalaxmi Pav Bhaji,Ellisbridge,4.3,500+,"['North,Indian']",200,28,28,28,GF 9/10 Dev complexnear parimal charasta opp. ...,C G Road,False,True,NaN
3,Fine Restaurants,328315,HIIT Meals,Vishala,--,Too Few,"['Fast,Food','Combo','Snacks','North,Indian','...",150,51,51,51,C11 Rajyash Rise Near Vishala Restaurant Vasna...,Vasna,False,False,NaN
4,Fine Restaurants,108879,Jay Jalaram Parotha House,Ellisbridge,3.9,100+,"['North,Indian']",250,29,29,29,Capital Commercial Centre Near UCO Bank Ashram...,Ashram Road,False,True,NaN

In [123]:
dataset_copy.to_csv('Swiggy_Final_Data.csv',index=False)